############# English navigation ##############

# main menu
[[main]]
name = "홈"
url = "/"
weight = 1

[[main]]
name = "소개"
url = "/introduction"
weight = 2

[[main]]
parent = "소개"
name = "회장단"
url = "/presidents"
weight = 1

[[main]]
parent = "소개"
name = "동문"
url = "/alumni"
weight = 2

[[main]]
parent = "소개"
name = "수상"
url = "/awards"
weight = 3

[[main]]
parent = "소개"
name = "연구"
url = "/research"
weight = 4

# ------------------------------------------------

[[main]]
name = "활동"
url = "/activities"
weight = 3

[[main]]
parent = "활동"
name = "커리큘럼"
url = "/curriculum"
weight = 1

[[main]]
parent = "활동"
name = "프로젝트"
url = "/projects"
weight = 2


[[main]]
parent = "활동"
name = "블로그"
url = "/blog"
weight = 3


[[main]]
parent = "활동"
name = "갤러리"
url = "/gallery"
weight = 4

# ------------------------------------------------

[[main]]
name = "지원하기"
url = "/apply"
weight = 5


[[main]]
name = "문의하기"
url = "/contact"
weight = 6


# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "지원하기"
url = "/apply"
weight = 1

[[footer]]
name = "문의하기"
url = "/contact"
weight = 2
